# -*- coding: utf-8 -*-
"""berttraining

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_UJ2wfRjpL-IdEuEq0cZf0YKWmc9Gy__
"""

!pip install datasets
# Install required libraries (if not installed)
!pip install transformers datasets pandas
import os
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import torch
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments
from datasets import Dataset
from sklearn.model_selection import train_test_split

# Disable W&B logging
os.environ["WANDB_DISABLED"] = "true"

import pandas as pd

dataset = pd.read_csv("/content/IMDB Dataset.csv")  # Load IMDb dataset
dataset['sentiment'] = dataset['sentiment'].map({'positive': 1, 'negative': 0})
print(dataset.head())

train_texts, test_texts, train_labels, test_labels = train_test_split(
    dataset["review"], dataset["sentiment"], test_size=0.2, random_state=42
)

# Check the first few training examples
print(train_texts.head(), train_labels.head())

import logging
logging.getLogger("huggingface_hub").setLevel(logging.ERROR)
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Convert Pandas DataFrame to Hugging Face Dataset
dataset = Dataset.from_pandas(df)

# Load BERT tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Define tokenization function
def tokenize_function(examples):
    return tokenizer(examples["review"], padding="max_length", truncation=True)

# Apply tokenization
tokenized_dataset = dataset.map(tokenize_function, batched=True)

# Display a sample
print(tokenized_dataset[0])

model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=2)

training_args = TrainingArguments(
    output_dir="./results",
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    weight_decay=0.01,
)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset
df = pd.read_csv("/content/IMDB Dataset.csv")
df["sentiment"] = df["sentiment"].map({"positive": 1, "negative": 0})  # Convert text labels to 0 & 1

# Prepare data
x = np.arange(len(df))
y = df["sentiment"].values
y_smooth = np.convolve(y, np.ones(50)/50, mode="same")

# Create subplots
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# 🌊 Stream Graph
axes[0].fill_between(x, y_smooth, color="#1DD1A1", alpha=0.6, label="Positive")
axes[0].fill_between(x, 0, y_smooth, where=(y_smooth < 0.5), color="#FF6B6B", alpha=0.6, label="Negative")
axes[0].set_title("Stream Graph of Sentiments")

# 📊 Box Plot
sns.boxplot(x="sentiment", y=np.random.rand(len(df)), hue="sentiment", data=df,
            palette={0: "#FF6B6B", 1: "#1DD1A1"}, ax=axes[1])
axes[1].set_title("Box Plot of Sentiments")

# 📉 Histogram
sns.histplot(df["sentiment"], bins=2, kde=True, palette={0: "#FF6B6B", 1: "#1DD1A1"}, ax=axes[2])
axes[2].set_title("Sentiment Distribution")

# Improve x-axis labels
for ax in axes:
    ax.set_xticks([0, 1])
    ax.set_xticklabels(["Negative", "Positive"], fontsize=11, fontweight="bold")
    ax.set_xlabel("Sentiment")

plt.tight_layout()
plt.show()

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
)

trainer.train()

metrics = trainer.evaluate()
print(metrics)

trainer.save_model("sentiment_model")  # Saves the trained model

# Save the tokenizer (Important!)
from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")  # Replace with your model's base
tokenizer.save_pretrained("sentiment_model")

from transformers import AutoModel
model = AutoModel.from_pretrained("path_to_save_model")

from transformers import pipeline

classifier = pipeline("sentiment-analysis", model="sentiment_model", tokenizer="sentiment_model")

result = classifier(["This is a great product!", "I hate this experience."])
print(result)

label_map = {
    "LABEL_1": "Positive",
    "LABEL_0": "Negative"
}

formatted_result = [{
    "label": label_map[item["label"]],
    "score": item["score"]
} for item in result]

print(formatted_result)

import os
print(os.listdir("sentiment_model"))

classifier = pipeline("sentiment-analysis", model="distilbert-base-uncased-finetuned-sst-2-english")

result = classifier(["I love this!", "This is terrible."])
print(result)

